### ISSUE TITLE
Unable to install, I have cordova 7.0.1

### ISSUE THREAD

**Issue by henrykode** [GruppoMeta/cordova-plugin-adv-tts#3]
Error: Failed to fetch plugin https://github.com/danieleguiducci/cordova-plugin-adv-tts.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 4294963228 Error output:
npm ERR! addLocal Could not install C:\Users\asus\AppData\Local\Temp\npm-6376-05e3b14b\git-cache-f0cc7e48\674065db899cd9e9e9f954c3ca1d17a7129c1dd7
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall read
npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\asus\AppData\Roaming\npm-cache\_logs\2017-05-22T12_46_53_969Z-debug.log

**Comment by sabirhusssain** [comment]
I'm also facing the same issue with Cordova 7.0.1. When I install any ionic native plugin then unable to build the app for Android. Installation completely removes the 'build' folder. Why it is happening?

**Comment by geoglis** [comment]
For plugin installtions in cordova 7.0.1 is a valid package.json required. I just added a pull request with a package.json for this plugin. 

You can also copy the plugin folder to your local machine an create it locally with:

$ plugman createpackagejson path/to/your/local/copy/the/plugin
$ cordova plugin add path/to/your/local/copy/the/plugin

**Comment by desmeit** [comment]
@geoglis sorry for that stupid question: How could I install from an pull request?
Thanks

**Comment by danieleugoletti** [comment]
Pull request merged
