### ISSUE TITLE
Function on result / on end?

### ISSUE THREAD

**Issue by desmeit** [GruppoMeta/cordova-plugin-adv-tts#5]
Hi @penguin86, @danieleguiducci, @

is it possible to run a function after the speech is finished?

Thanks a lot.

**Comment by danieleugoletti** [comment]
HI
you can use:

```
advtts.speak(' you text');
advtts.onChange(function () {
    if (!advtts.speaking()) {
        // end
    }
});

```

**Comment by desmeit** [comment]
Hi @danieleguiducci 
thank you. this is working on IOS but not on android.
could you take a look on it?

**Comment by saqimtiaz** [comment]
@desmeit @danieleguiducci 

Adding `send("stopSpeak");` after line [78 in advtts.java](https://github.com/GruppoMeta/cordova-plugin-adv-tts/blob/master/src/android/it/gruppometa/cordova/Advtts.java#L78) should resolve the problem
